require('dotenv').config();
const { Pool } = require('pg');

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: { rejectUnauthorized: false }
});

const curriculum = [
  // ── STAGE 1 (Grade 1) ─────────────────────────────────────
  { grade:1, stage:1, strand:'Thinking and Working Scientifically', substrand:'Scientific Enquiry: Purpose and Planning', code:'1TWSp.01', objective:'Ask questions about the world around us and talk about how to find answers.' },
  { grade:1, stage:1, strand:'Thinking and Working Scientifically', substrand:'Scientific Enquiry: Purpose and Planning', code:'1TWSp.02', objective:'Make predictions about what they think will happen.' },
  { grade:1, stage:1, strand:'Thinking and Working Scientifically', substrand:'Carrying out Scientific Enquiry', code:'1TWSc.01', objective:'Sort and group objects, materials and living things based on observations of the similarities and differences between them.' },
  { grade:1, stage:1, strand:'Thinking and Working Scientifically', substrand:'Carrying out Scientific Enquiry', code:'1TWSc.02', objective:'Use given equipment appropriately.' },
  { grade:1, stage:1, strand:'Thinking and Working Scientifically', substrand:'Carrying out Scientific Enquiry', code:'1TWSc.03', objective:'Take measurements in non-standard units.' },
  { grade:1, stage:1, strand:'Thinking and Working Scientifically', substrand:'Carrying out Scientific Enquiry', code:'1TWSc.04', objective:'Follow instructions safely when doing practical work.' },
  { grade:1, stage:1, strand:'Thinking and Working Scientifically', substrand:'Carrying out Scientific Enquiry', code:'1TWSc.05', objective:'Collect and record observations and/or measurements by annotating images and completing simple tables.' },
  { grade:1, stage:1, strand:'Thinking and Working Scientifically', substrand:'Analysis, Evaluation and Conclusions', code:'1TWSa.01', objective:'Describe what happened during an enquiry and if it matched their predictions.' },
  { grade:1, stage:1, strand:'Biology', substrand:'Structure and Function', code:'1Bs.01', objective:'Recognise and name the major parts of familiar flowering plants (limited to roots, leaves, stems and flowers).' },
  { grade:1, stage:1, strand:'Biology', substrand:'Structure and Function', code:'1Bs.02', objective:'Identify the senses (limited to sight, hearing, taste, smell and touch) and what they detect, linking each to the correct body part.' },
  { grade:1, stage:1, strand:'Biology', substrand:'Structure and Function', code:'1Bs.03', objective:'Recognise and name the major external parts of the human body.' },
  { grade:1, stage:1, strand:'Biology', substrand:'Life Processes', code:'1Bp.01', objective:'Identify living things and things that have never been alive.' },
  { grade:1, stage:1, strand:'Biology', substrand:'Life Processes', code:'1Bp.02', objective:'Know that animals, including humans, need air, water and suitable food to survive.' },
  { grade:1, stage:1, strand:'Biology', substrand:'Life Processes', code:'1Bp.03', objective:'Know that plants need light and water to survive.' },
  { grade:1, stage:1, strand:'Biology', substrand:'Life Processes', code:'1Bp.04', objective:'Describe how humans are similar to and different from each other.' },
  { grade:1, stage:1, strand:'Chemistry', substrand:'Materials and Their Structure', code:'1Cm.01', objective:'Identify, name, describe, sort and group common materials, including wood, plastic, metal, glass, rock, paper and fabric.' },
  { grade:1, stage:1, strand:'Chemistry', substrand:'Materials and Their Structure', code:'1Cm.02', objective:'Understand the difference between an object and a material.' },
  { grade:1, stage:1, strand:'Chemistry', substrand:'Properties of Materials', code:'1Cp.01', objective:'Understand that all materials have a variety of properties.' },
  { grade:1, stage:1, strand:'Chemistry', substrand:'Properties of Materials', code:'1Cp.02', objective:'Describe common materials in terms of their properties.' },
  { grade:1, stage:1, strand:'Chemistry', substrand:'Changes to Materials', code:'1Cc.01', objective:'Describe how materials can be changed by physical action, e.g. stretching, compressing, bending and twisting.' },
  { grade:1, stage:1, strand:'Physics', substrand:'Forces and Energy', code:'1Pf.01', objective:'Explore, talk about and describe the movement of familiar objects.' },
  { grade:1, stage:1, strand:'Physics', substrand:'Forces and Energy', code:'1Pf.02', objective:'Describe pushes and pulls as forces.' },
  { grade:1, stage:1, strand:'Physics', substrand:'Forces and Energy', code:'1Pf.03', objective:'Explore that some objects float and some sink.' },
  { grade:1, stage:1, strand:'Physics', substrand:'Light and Sound', code:'1Ps.01', objective:'Identify different sources of sound.' },
  { grade:1, stage:1, strand:'Physics', substrand:'Light and Sound', code:'1Ps.02', objective:'Explore that as sound travels from a source it becomes quieter.' },
  { grade:1, stage:1, strand:'Physics', substrand:'Electricity and Magnetism', code:'1Pe.01', objective:'Identify things that require electricity to work.' },
  { grade:1, stage:1, strand:'Physics', substrand:'Electricity and Magnetism', code:'1Pe.02', objective:'Explore, talk about and describe what happens when magnets approach and touch different materials.' },
  { grade:1, stage:1, strand:'Earth and Space', substrand:'Planet Earth', code:'1ESp.01', objective:'Know that Earth is mostly covered in water.' },
  { grade:1, stage:1, strand:'Earth and Space', substrand:'Planet Earth', code:'1ESp.02', objective:'Describe land as being made of rock and soil.' },
  { grade:1, stage:1, strand:'Earth and Space', substrand:'Earth in Space', code:'1ESs.01', objective:'Know that Earth is the planet on which we live.' },
  { grade:1, stage:1, strand:'Earth and Space', substrand:'Earth in Space', code:'1ESs.02', objective:'Describe the Sun as a source of heat and light, and as one of many stars.' },

  // ── STAGE 2 (Grade 2) ─────────────────────────────────────
  { grade:2, stage:2, strand:'Thinking and Working Scientifically', substrand:'Models and Representations', code:'2TWSm.01', objective:'Know that a model represents an object or idea in a clear way.' },
  { grade:2, stage:2, strand:'Thinking and Working Scientifically', substrand:'Models and Representations', code:'2TWSm.02', objective:'Make and use a physical model of a familiar system or idea.' },
  { grade:2, stage:2, strand:'Thinking and Working Scientifically', substrand:'Models and Representations', code:'2TWSm.03', objective:'Describe the difference between a diagram and a picture.' },
  { grade:2, stage:2, strand:'Thinking and Working Scientifically', substrand:'Scientific Enquiry: Purpose and Planning', code:'2TWSp.01', objective:'Ask questions about the world around us and talk about how to find answers.' },
  { grade:2, stage:2, strand:'Thinking and Working Scientifically', substrand:'Scientific Enquiry: Purpose and Planning', code:'2TWSp.02', objective:'Make predictions about what they think will happen.' },
  { grade:2, stage:2, strand:'Thinking and Working Scientifically', substrand:'Analysis, Evaluation and Conclusions', code:'2TWSa.01', objective:'Describe what happened during an enquiry and if it matched their predictions.' },
  { grade:2, stage:2, strand:'Thinking and Working Scientifically', substrand:'Analysis, Evaluation and Conclusions', code:'2TWSa.02', objective:'Identify simple patterns in results, e.g. increasing and decreasing patterns.' },
  { grade:2, stage:2, strand:'Thinking and Working Scientifically', substrand:'Analysis, Evaluation and Conclusions', code:'2TWSa.03', objective:'Present and interpret results using tables and block graphs.' },
  { grade:2, stage:2, strand:'Biology', substrand:'Structure and Function', code:'2Bs.01', objective:'Compare how animals, including humans, are similar and different in their external body parts and skin covering.' },
  { grade:2, stage:2, strand:'Biology', substrand:'Structure and Function', code:'2Bs.02', objective:'Identify the different types of human teeth, explain how they are suited to their functions and describe how to care for teeth.' },
  { grade:2, stage:2, strand:'Biology', substrand:'Life Processes', code:'2Bp.01', objective:'Know that humans need to manage diet, maintain hygiene and move regularly to be healthy.' },
  { grade:2, stage:2, strand:'Biology', substrand:'Life Processes', code:'2Bp.02', objective:'Describe what illness is and describe the common signs of illness in humans.' },
  { grade:2, stage:2, strand:'Biology', substrand:'Life Processes', code:'2Bp.03', objective:'Describe how the offspring of animals, including humans, change as they become older.' },
  { grade:2, stage:2, strand:'Biology', substrand:'Life Processes', code:'2Bp.04', objective:'Know that animals, including humans, produce offspring that have a combination of features from their parents.' },
  { grade:2, stage:2, strand:'Biology', substrand:'Ecosystems', code:'2Be.01', objective:'Know that an environment in which a plant or animal naturally lives is its habitat.' },
  { grade:2, stage:2, strand:'Biology', substrand:'Ecosystems', code:'2Be.02', objective:'Know that different habitats contain different plants and animals.' },
  { grade:2, stage:2, strand:'Biology', substrand:'Ecosystems', code:'2Be.03', objective:'Identify similarities and differences between local environments in terms of hot, cold, dry, wet, many plants, few plants, many animals and few animals.' },
  { grade:2, stage:2, strand:'Chemistry', substrand:'Materials and Their Structure', code:'2Cm.01', objective:'Understand that some materials occur naturally and others are manufactured.' },
  { grade:2, stage:2, strand:'Chemistry', substrand:'Properties of Materials', code:'2Cp.01', objective:'Describe a property as a characteristic of a material and understand that materials can have more than one property.' },
  { grade:2, stage:2, strand:'Chemistry', substrand:'Properties of Materials', code:'2Cp.02', objective:'Explain why materials are chosen for specific purposes on the basis of their properties.' },
  { grade:2, stage:2, strand:'Chemistry', substrand:'Properties of Materials', code:'2Cp.03', objective:'Know that materials can be tested to determine their properties.' },
  { grade:2, stage:2, strand:'Chemistry', substrand:'Changes to Materials', code:'2Cc.01', objective:'Know that some changes can turn a material into a different material.' },
  { grade:2, stage:2, strand:'Physics', substrand:'Forces and Energy', code:'2Pf.01', objective:'Know that forces can change the movement of an object.' },
  { grade:2, stage:2, strand:'Physics', substrand:'Forces and Energy', code:'2Pf.02', objective:'Know that forces can change the shape of an object.' },
  { grade:2, stage:2, strand:'Physics', substrand:'Forces and Energy', code:'2Pf.03', objective:'Recognise that things will only speed up, slow down or change direction when something else causes them to do so.' },
  { grade:2, stage:2, strand:'Physics', substrand:'Light and Sound', code:'2Ps.01', objective:'Know that there are many light sources, including the Sun.' },
  { grade:2, stage:2, strand:'Physics', substrand:'Light and Sound', code:'2Ps.02', objective:'Know that darkness is the absence of light.' },
  { grade:2, stage:2, strand:'Physics', substrand:'Electricity and Magnetism', code:'2Pe.01', objective:'Identify how we use electricity and describe how to be safe with it.' },
  { grade:2, stage:2, strand:'Physics', substrand:'Electricity and Magnetism', code:'2Pe.02', objective:'Recognise the components of simple circuits (limited to cells, wires and lamps).' },
  { grade:2, stage:2, strand:'Physics', substrand:'Electricity and Magnetism', code:'2Pe.03', objective:'Explore the construction of simple series circuits (limited to cells, wires and lamps).' },
  { grade:2, stage:2, strand:'Earth and Space', substrand:'Planet Earth', code:'2ESp.01', objective:'Describe and compare different types of rock.' },
  { grade:2, stage:2, strand:'Earth and Space', substrand:'Planet Earth', code:'2ESp.02', objective:'Know rocks are extracted from the Earth in different ways, including from quarries, mines and riverbeds.' },
  { grade:2, stage:2, strand:'Earth and Space', substrand:'Planet Earth', code:'2ESp.03', objective:'Know that human activity can affect the environment.' },
  { grade:2, stage:2, strand:'Earth and Space', substrand:'Earth in Space', code:'2ESs.01', objective:'Describe the apparent movement of the Sun during the day.' },

  // ── STAGE 3 (Grade 3) ─────────────────────────────────────
  { grade:3, stage:3, strand:'Biology', substrand:'Structure and Function', code:'3Bs.01', objective:'Describe the function of the major parts of flowering plants (limited to roots, leaves, stems and flowers).' },
  { grade:3, stage:3, strand:'Biology', substrand:'Structure and Function', code:'3Bs.02', objective:'Identify the distinguishing features of different groups of animals, including fish, reptiles, mammals, birds, amphibians and insects.' },
  { grade:3, stage:3, strand:'Biology', substrand:'Structure and Function', code:'3Bs.03', objective:'Identify some of the important organs in humans (limited to brain, heart, stomach, intestine and lungs) and describe their functions.' },
  { grade:3, stage:3, strand:'Biology', substrand:'Life Processes', code:'3Bp.01', objective:'Describe differences between things that are living, that were once alive and that have never lived.' },
  { grade:3, stage:3, strand:'Biology', substrand:'Life Processes', code:'3Bp.02', objective:'Know that life processes common to plants and animals include nutrition, growth, movement and reproduction.' },
  { grade:3, stage:3, strand:'Biology', substrand:'Life Processes', code:'3Bp.03', objective:'Know that plants need appropriate conditions, including temperature, light and water, to be healthy.' },
  { grade:3, stage:3, strand:'Biology', substrand:'Life Processes', code:'3Bp.04', objective:'Describe and compare how the offspring of different animals grow into adults, including humans, birds, frogs and butterflies.' },
  { grade:3, stage:3, strand:'Biology', substrand:'Ecosystems', code:'3Be.01', objective:'Identify and describe simple food chains, where plants are producers and animals are consumers of plants and/or other animals.' },
  { grade:3, stage:3, strand:'Chemistry', substrand:'Materials and Their Structure', code:'3Cm.01', objective:'Know that materials can be solids, liquids or gases.' },
  { grade:3, stage:3, strand:'Chemistry', substrand:'Materials and Their Structure', code:'3Cm.02', objective:'Understand that a mixture contains two or more materials, where the materials can be physically separated.' },
  { grade:3, stage:3, strand:'Chemistry', substrand:'Properties of Materials', code:'3Cp.01', objective:'Describe differences in the properties of solids and liquids.' },
  { grade:3, stage:3, strand:'Chemistry', substrand:'Properties of Materials', code:'3Cp.02', objective:'Understand that materials, generally, retain their properties within a mixture.' },
  { grade:3, stage:3, strand:'Chemistry', substrand:'Properties of Materials', code:'3Cp.03', objective:'Describe how to separate solid/solid mixtures based on the physical properties of the solids.' },
  { grade:3, stage:3, strand:'Chemistry', substrand:'Properties of Materials', code:'3Cp.04', objective:'Describe how to separate a mixture of an insoluble solid and a liquid.' },
  { grade:3, stage:3, strand:'Chemistry', substrand:'Changes to Materials', code:'3Cc.01', objective:'Know that when a solid dissolves in a liquid the solid is still present, and this is an example of making a mixture.' },
  { grade:3, stage:3, strand:'Physics', substrand:'Forces and Energy', code:'3Pf.01', objective:'Know that forces can be measured with a forcemeter and the standard unit of force is the newton (N).' },
  { grade:3, stage:3, strand:'Physics', substrand:'Forces and Energy', code:'3Pf.02', objective:'Know that gravity on Earth is a force that pulls towards the centre of the Earth.' },
  { grade:3, stage:3, strand:'Physics', substrand:'Forces and Energy', code:'3Pf.03', objective:'Know that friction is a force created between surfaces when they move against each other and it makes this movement harder.' },
  { grade:3, stage:3, strand:'Physics', substrand:'Forces and Energy', code:'3Pf.04', objective:'Describe how smooth and rough surfaces can generate different amounts of friction.' },
  { grade:3, stage:3, strand:'Physics', substrand:'Light and Sound', code:'3Ps.01', objective:'Investigate and describe how light can pass through some materials and is blocked by others, and use the terms transparent, translucent and opaque.' },
  { grade:3, stage:3, strand:'Physics', substrand:'Light and Sound', code:'3Ps.02', objective:'Know that shadows are formed when light from a source is blocked by an object.' },
  { grade:3, stage:3, strand:'Physics', substrand:'Light and Sound', code:'3Ps.03', objective:'Investigate and describe how the size of a shadow is affected by the position of the object and the position of the light source.' },
  { grade:3, stage:3, strand:'Physics', substrand:'Electricity and Magnetism', code:'3Pe.01', objective:'Describe magnets as having a north pole and a south pole.' },
  { grade:3, stage:3, strand:'Physics', substrand:'Electricity and Magnetism', code:'3Pe.02', objective:'Describe how magnets interact when near each other, using the terms repel and attract.' },
  { grade:3, stage:3, strand:'Physics', substrand:'Electricity and Magnetism', code:'3Pe.03', objective:'Investigate how some materials are magnetic but many are not.' },
  { grade:3, stage:3, strand:'Earth and Space', substrand:'Planet Earth', code:'3ESp.01', objective:'Know that planet Earth is the source of all the materials we use and that many useful materials, including oil, natural gas and metals, come from or are found in rocks.' },
  { grade:3, stage:3, strand:'Earth and Space', substrand:'Planet Earth', code:'3ESp.02', objective:'Know that fossils are impressions, or remains, of things that were once alive.' },
  { grade:3, stage:3, strand:'Earth and Space', substrand:'Earth in Space', code:'3ESs.01', objective:'Describe the regular change in the position and appearance of the Moon.' },
  { grade:3, stage:3, strand:'Earth and Space', substrand:'Earth in Space', code:'3ESs.02', objective:'Describe the relative movement of the Earth and Moon.' },
  { grade:3, stage:3, strand:'Earth and Space', substrand:'Earth in Space', code:'3ESs.03', objective:'Describe the Earth, Sun and Moon as approximately spherical.' },

  // ── STAGE 4 (Grade 4) ─────────────────────────────────────
  { grade:4, stage:4, strand:'Biology', substrand:'Structure and Function', code:'4Bs.01', objective:'Identify some of the important bones in the human body (limited to skull, jaw, rib cage, hip, spine, leg bones and arm bones).' },
  { grade:4, stage:4, strand:'Biology', substrand:'Structure and Function', code:'4Bs.02', objective:'Know that bones move because pairs of muscles that are attached to them contract and relax.' },
  { grade:4, stage:4, strand:'Biology', substrand:'Structure and Function', code:'4Bs.03', objective:'Describe the important functions of skeletons (limited to protecting and supporting organs, enabling movement and giving shape to the body).' },
  { grade:4, stage:4, strand:'Biology', substrand:'Structure and Function', code:'4Bs.04', objective:'Know that some animals have an exoskeleton.' },
  { grade:4, stage:4, strand:'Biology', substrand:'Structure and Function', code:'4Bs.05', objective:'Identify vertebrates as animals with a backbone and invertebrates as animals without a backbone.' },
  { grade:4, stage:4, strand:'Biology', substrand:'Life Processes', code:'4Bp.01', objective:'Know that medicines can be used to treat some illnesses, and describe how to use them safely.' },
  { grade:4, stage:4, strand:'Biology', substrand:'Life Processes', code:'4Bp.02', objective:'Know that plants and animals can have infectious diseases, and vaccinations can prevent some infectious diseases of animals.' },
  { grade:4, stage:4, strand:'Biology', substrand:'Life Processes', code:'4Bp.03', objective:'Know that plants and animals need energy to grow, live and be healthy, and plants get their energy from light while animals get their energy from eating plants or other animals.' },
  { grade:4, stage:4, strand:'Biology', substrand:'Life Processes', code:'4Bp.04', objective:'Describe the importance of movement in maintaining human health.' },
  { grade:4, stage:4, strand:'Biology', substrand:'Ecosystems', code:'4Be.01', objective:'Know that different animals are found in, and suited to, different habitats.' },
  { grade:4, stage:4, strand:'Biology', substrand:'Ecosystems', code:'4Be.02', objective:'Know plants and animals can survive in environments other than their habitats.' },
  { grade:4, stage:4, strand:'Biology', substrand:'Ecosystems', code:'4Be.03', objective:'Describe food chains as being made of producers and consumers, and classify consumers as herbivores, omnivores, carnivores, predators and/or prey.' },
  { grade:4, stage:4, strand:'Chemistry', substrand:'Materials and Their Structure', code:'4Cm.01', objective:'Describe the particle model for solids and liquids.' },
  { grade:4, stage:4, strand:'Chemistry', substrand:'Materials and Their Structure', code:'4Cm.02', objective:'Understand the difference between materials, substances and particles.' },
  { grade:4, stage:4, strand:'Chemistry', substrand:'Materials and Their Structure', code:'4Cm.03', objective:'Know that particles are in constant motion, even when in a solid.' },
  { grade:4, stage:4, strand:'Chemistry', substrand:'Properties of Materials', code:'4Cp.01', objective:'Use the particle model to explain the properties of solids and liquids.' },
  { grade:4, stage:4, strand:'Chemistry', substrand:'Properties of Materials', code:'4Cp.02', objective:'Describe and explain how some solids can behave like liquids (e.g. powders), referring to the particle model.' },
  { grade:4, stage:4, strand:'Chemistry', substrand:'Changes to Materials', code:'4Cc.01', objective:'Describe solidification/freezing and melting, using the particle model to describe the change of state.' },
  { grade:4, stage:4, strand:'Chemistry', substrand:'Changes to Materials', code:'4Cc.02', objective:'Understand that the change of state of a substance is a physical process.' },
  { grade:4, stage:4, strand:'Chemistry', substrand:'Changes to Materials', code:'4Cc.03', objective:'Know that some substances will react with another substance to produce one or more new substances and this is called a chemical reaction.' },
  { grade:4, stage:4, strand:'Physics', substrand:'Forces and Energy', code:'4Pf.01', objective:'Know that energy is present in all matter and in sound, light and heat.' },
  { grade:4, stage:4, strand:'Physics', substrand:'Forces and Energy', code:'4Pf.02', objective:'Know that energy cannot be made, lost, used up or destroyed but it can be transferred.' },
  { grade:4, stage:4, strand:'Physics', substrand:'Forces and Energy', code:'4Pf.03', objective:'Know that energy is required for any movement or action to happen.' },
  { grade:4, stage:4, strand:'Physics', substrand:'Forces and Energy', code:'4Pf.04', objective:'Know that not all energy is transferred from one object to another, but often some energy during a process can be transferred to the surrounding environment.' },
  { grade:4, stage:4, strand:'Physics', substrand:'Light and Sound', code:'4Ps.01', objective:'Know that light travels in straight lines and this can be represented with ray diagrams.' },
  { grade:4, stage:4, strand:'Physics', substrand:'Light and Sound', code:'4Ps.02', objective:'Know that light can reflect off surfaces.' },
  { grade:4, stage:4, strand:'Physics', substrand:'Light and Sound', code:'4Ps.03', objective:'Describe how objects which are not light sources are seen.' },
  { grade:4, stage:4, strand:'Physics', substrand:'Electricity and Magnetism', code:'4Pe.01', objective:'Know that an electrical device will not work if there is a break in the circuit.' },
  { grade:4, stage:4, strand:'Physics', substrand:'Electricity and Magnetism', code:'4Pe.02', objective:'Describe how a simple switch is used to open and close a circuit.' },
  { grade:4, stage:4, strand:'Physics', substrand:'Electricity and Magnetism', code:'4Pe.03', objective:'Describe how changing the number or type of components in a series circuit can make a lamp brighter or dimmer.' },
  { grade:4, stage:4, strand:'Physics', substrand:'Electricity and Magnetism', code:'4Pe.04', objective:'Know some materials are good electrical conductors, especially metals, and some are good electrical insulators.' },
  { grade:4, stage:4, strand:'Earth and Space', substrand:'Planet Earth', code:'4ESp.01', objective:'Describe the model of the structure of the Earth which includes a core, a mantle and a crust.' },
  { grade:4, stage:4, strand:'Earth and Space', substrand:'Planet Earth', code:'4ESp.02', objective:'Describe common features of volcanoes and know they are found at breaks in the Earth\'s crust.' },
  { grade:4, stage:4, strand:'Earth and Space', substrand:'Planet Earth', code:'4ESp.03', objective:'Know that the Earth\'s crust moves and when parts move suddenly this is called an earthquake.' },
  { grade:4, stage:4, strand:'Earth and Space', substrand:'Earth in Space', code:'4ESs.01', objective:'Explain why the spinning of the Earth on its axis leads to the apparent movement of the Sun, night and day, and changes in shadows.' },
  { grade:4, stage:4, strand:'Earth and Space', substrand:'Earth in Space', code:'4ESs.02', objective:'Name the planets in the Solar System.' },
  { grade:4, stage:4, strand:'Earth and Space', substrand:'Earth in Space', code:'4ESs.03', objective:'Know that the Sun is at the centre of the Solar System.' },
  { grade:4, stage:4, strand:'Earth and Space', substrand:'Earth in Space', code:'4ESs.04', objective:'Know that planetary systems can contain stars, planets, asteroids and comets.' },

  // ── STAGE 5 (Grade 5) ─────────────────────────────────────
  { grade:5, stage:5, strand:'Biology', substrand:'Structure and Function', code:'5Bs.01', objective:'Know that not all plants produce flowers.' },
  { grade:5, stage:5, strand:'Biology', substrand:'Structure and Function', code:'5Bs.02', objective:'Identify the parts of a flower (limited to petals, sepals, anthers, filaments, stamens, stigma, style, carpel, and ovary).' },
  { grade:5, stage:5, strand:'Biology', substrand:'Structure and Function', code:'5Bs.03', objective:'Describe the functions of the parts of a flower (limited to petals, anthers, stigma and ovary).' },
  { grade:5, stage:5, strand:'Biology', substrand:'Structure and Function', code:'5Bs.04', objective:'Describe the human digestive system, including the functions of the organs involved (limited to mouth, oesophagus, stomach, small intestine, large intestine and anus).' },
  { grade:5, stage:5, strand:'Biology', substrand:'Life Processes', code:'5Bp.01', objective:'Know that animals, including humans, need an adequate, balanced diet in order to be healthy.' },
  { grade:5, stage:5, strand:'Biology', substrand:'Life Processes', code:'5Bp.02', objective:'Know the stages in the life cycle of a flowering plant.' },
  { grade:5, stage:5, strand:'Biology', substrand:'Life Processes', code:'5Bp.03', objective:'Describe how flowering plants reproduce by pollination, fruit and seed production, and seed dispersal.' },
  { grade:5, stage:5, strand:'Biology', substrand:'Life Processes', code:'5Bp.04', objective:'Describe seed germination and know that seeds, in general, require water and an appropriate temperature to germinate.' },
  { grade:5, stage:5, strand:'Biology', substrand:'Ecosystems', code:'5Be.01', objective:'Describe how plants and animals are adapted to environments that are hot, cold, wet and/or dry.' },
  { grade:5, stage:5, strand:'Biology', substrand:'Ecosystems', code:'5Be.02', objective:'Describe how flowering plants are adapted to attract pollinators and promote seed dispersal.' },
  { grade:5, stage:5, strand:'Biology', substrand:'Ecosystems', code:'5Be.03', objective:'Describe the common adaptations of predator and prey animals.' },
  { grade:5, stage:5, strand:'Chemistry', substrand:'Materials and Their Structure', code:'5Cm.01', objective:'Use the particle model to describe solid, liquids (including solutions) and gases.' },
  { grade:5, stage:5, strand:'Chemistry', substrand:'Materials and Their Structure', code:'5Cm.02', objective:'Understand that substances can be gaseous and know the common gases at room temperature (limited to oxygen, carbon dioxide, water vapour, nitrogen and hydrogen).' },
  { grade:5, stage:5, strand:'Chemistry', substrand:'Properties of Materials', code:'5Cp.01', objective:'Know that the ability of a solid to dissolve and the ability of a liquid to act as a solvent are properties of the solid and liquid.' },
  { grade:5, stage:5, strand:'Chemistry', substrand:'Properties of Materials', code:'5Cp.02', objective:'Know the main properties of water (limited to boiling point, melting point, expands when it solidifies, and its ability to dissolve a range of substances).' },
  { grade:5, stage:5, strand:'Chemistry', substrand:'Changes to Materials', code:'5Cc.01', objective:'Describe the processes of evaporation and condensation, using the particle model and relating the processes to changes in temperature.' },
  { grade:5, stage:5, strand:'Chemistry', substrand:'Changes to Materials', code:'5Cc.02', objective:'Understand that dissolving is a reversible process and investigate how to separate the solvent and solute after a solution is formed.' },
  { grade:5, stage:5, strand:'Chemistry', substrand:'Changes to Materials', code:'5Cc.03', objective:'Investigate and describe the process of dissolving (using the terms solute, solvent and solution), and relate it to making a mixture.' },
  { grade:5, stage:5, strand:'Physics', substrand:'Forces and Energy', code:'5Pf.01', objective:'Identify a range of forces (limited to gravity, applied forces, normal forces, upthrust, friction, air resistance and water resistance).' },
  { grade:5, stage:5, strand:'Physics', substrand:'Forces and Energy', code:'5Pf.02', objective:'Know that an object may have multiple forces acting upon it, even when at rest.' },
  { grade:5, stage:5, strand:'Physics', substrand:'Forces and Energy', code:'5Pf.03', objective:'Use force diagrams to show the name and direction of forces acting on an object.' },
  { grade:5, stage:5, strand:'Physics', substrand:'Light and Sound', code:'5Ps.01', objective:'Investigate how sounds are made by vibrating sources.' },
  { grade:5, stage:5, strand:'Physics', substrand:'Light and Sound', code:'5Ps.02', objective:'Describe sounds in terms of high or low pitch and loud or quiet volume.' },
  { grade:5, stage:5, strand:'Physics', substrand:'Light and Sound', code:'5Ps.03', objective:'Investigate how to change the volume and pitch of sounds.' },
  { grade:5, stage:5, strand:'Physics', substrand:'Electricity and Magnetism', code:'5Pe.01', objective:'Know the difference between a magnet and a magnetic material.' },
  { grade:5, stage:5, strand:'Physics', substrand:'Electricity and Magnetism', code:'5Pe.02', objective:'Know that forces act over a distance between magnets, and between a magnet and a magnetic material.' },
  { grade:5, stage:5, strand:'Physics', substrand:'Electricity and Magnetism', code:'5Pe.03', objective:'Know that magnets can have different magnetic strengths.' },
  { grade:5, stage:5, strand:'Earth and Space', substrand:'Planet Earth', code:'5ESp.01', objective:'Know that the Earth is surrounded by a layer of air called the atmosphere, which is a mixture of different gases (including nitrogen, carbon dioxide and oxygen).' },
  { grade:5, stage:5, strand:'Earth and Space', substrand:'Planet Earth', code:'5ESp.02', objective:'Understand that most water on Earth is not pure and has dissolved substances in it.' },
  { grade:5, stage:5, strand:'Earth and Space', substrand:'Planet Earth', code:'5ESp.03', objective:'Understand that pollution is the introduction of substances by humans that harm the environment and identify examples of pollution.' },
  { grade:5, stage:5, strand:'Earth and Space', substrand:'Cycles on Earth', code:'5ESc.01', objective:'Describe the water cycle (limited to evaporation, condensation and precipitation).' },
  { grade:5, stage:5, strand:'Earth and Space', substrand:'Earth in Space', code:'5ESs.01', objective:'Describe the orbit of the Earth around the Sun (limited to slight ellipse, anticlockwise direction and the duration).' },
  { grade:5, stage:5, strand:'Earth and Space', substrand:'Earth in Space', code:'5ESs.02', objective:'Describe how the tilt of the Earth can create different seasons in different places.' },
  { grade:5, stage:5, strand:'Earth and Space', substrand:'Earth in Space', code:'5ESs.03', objective:'Know that a satellite is an object in space that orbits a larger object and a moon is a natural satellite that orbits a planet.' },

  // ── STAGE 6 (Grade 6) ─────────────────────────────────────
  { grade:6, stage:6, strand:'Biology', substrand:'Structure and Function', code:'6Bs.01', objective:'Describe the human circulatory system in terms of the heart pumping blood through arteries, capillaries and veins, describe its function (limited to transporting oxygen, nutrients and waste).' },
  { grade:6, stage:6, strand:'Biology', substrand:'Structure and Function', code:'6Bs.02', objective:'Describe the human respiratory system in terms of oxygen from the air moving into the blood in the lungs and the removal of carbon dioxide.' },
  { grade:6, stage:6, strand:'Biology', substrand:'Structure and Function', code:'6Bs.03', objective:'Name the parts of the human reproductive system.' },
  { grade:6, stage:6, strand:'Biology', substrand:'Life Processes', code:'6Bp.01', objective:'Describe the physical changes that take place during puberty in humans.' },
  { grade:6, stage:6, strand:'Biology', substrand:'Life Processes', code:'6Bp.02', objective:'Know that some diseases can be caused by infection with viruses, bacteria, parasites or fungi that can be passed from one host to another.' },
  { grade:6, stage:6, strand:'Biology', substrand:'Life Processes', code:'6Bp.03', objective:'Describe how good hygiene can control the spread of infectious diseases that are transmitted in water, food and body fluids.' },
  { grade:6, stage:6, strand:'Biology', substrand:'Life Processes', code:'6Bp.04', objective:'Know that humans have defence mechanisms against infectious diseases, including skin, stomach acid and mucus.' },
  { grade:6, stage:6, strand:'Biology', substrand:'Ecosystems', code:'6Be.01', objective:'Interpret food webs and identify food chains within them.' },
  { grade:6, stage:6, strand:'Biology', substrand:'Ecosystems', code:'6Be.02', objective:'Know that some substances can be toxic and damage living things, and that these substances can move through a food chain/web.' },
  { grade:6, stage:6, strand:'Biology', substrand:'Ecosystems', code:'6Be.03', objective:'Identify the energy source of a food chain/web and describe how energy is transferred through a food chain/web.' },
  { grade:6, stage:6, strand:'Chemistry', substrand:'Properties of Materials', code:'6Cp.01', objective:'Know that the temperature at which a substance changes state is a property of the substance.' },
  { grade:6, stage:6, strand:'Chemistry', substrand:'Properties of Materials', code:'6Cp.02', objective:'Know that gases have properties, including mass.' },
  { grade:6, stage:6, strand:'Chemistry', substrand:'Properties of Materials', code:'6Cp.03', objective:'Understand that electrical conductivity and thermal conductivity are properties of a substance.' },
  { grade:6, stage:6, strand:'Chemistry', substrand:'Changes to Materials', code:'6Cc.01', objective:'Identify and describe physical changes that are reversible.' },
  { grade:6, stage:6, strand:'Chemistry', substrand:'Changes to Materials', code:'6Cc.02', objective:'Describe how temperature affects solids dissolving in liquids and relate it to the particle model.' },
  { grade:6, stage:6, strand:'Chemistry', substrand:'Changes to Materials', code:'6Cc.03', objective:'Describe the difference between boiling and evaporation.' },
  { grade:6, stage:6, strand:'Chemistry', substrand:'Changes to Materials', code:'6Cc.04', objective:'Understand that chemical reactions involve substances, called reactants, interacting to form new substances, called products.' },
  { grade:6, stage:6, strand:'Chemistry', substrand:'Changes to Materials', code:'6Cc.05', objective:'Observe and describe the evidence that a chemical reaction has taken place (limited to a gas being produced, colour change and change in temperature).' },
  { grade:6, stage:6, strand:'Physics', substrand:'Forces and Energy', code:'6Pf.01', objective:'Describe the difference between mass, measured in kilograms (kg), and weight, measured in newtons (N).' },
  { grade:6, stage:6, strand:'Physics', substrand:'Forces and Energy', code:'6Pf.02', objective:'Describe the effect of gravity and know that when gravity changes, the weight of an object changes but the mass does not.' },
  { grade:6, stage:6, strand:'Physics', substrand:'Forces and Energy', code:'6Pf.03', objective:'Use force diagrams to show the name, size and direction of forces acting on an object.' },
  { grade:6, stage:6, strand:'Physics', substrand:'Forces and Energy', code:'6Pf.04', objective:'Describe the effect of different forces on an object at rest and in motion.' },
  { grade:6, stage:6, strand:'Physics', substrand:'Forces and Energy', code:'6Pf.05', objective:'Recognise that the mass and shape of an object can affect if it floats or sinks.' },
  { grade:6, stage:6, strand:'Physics', substrand:'Light and Sound', code:'6Ps.01', objective:'Describe how a ray of light changes direction when it is reflected from a plane mirror.' },
  { grade:6, stage:6, strand:'Physics', substrand:'Light and Sound', code:'6Ps.02', objective:'Describe how a ray of light changes direction when it travels through different mediums and know that this is called refraction.' },
  { grade:6, stage:6, strand:'Physics', substrand:'Electricity and Magnetism', code:'6Pe.01', objective:'Use diagrams and conventional symbols to represent, make and compare series and parallel circuits that include cells, switches, lamps and buzzers.' },
  { grade:6, stage:6, strand:'Physics', substrand:'Electricity and Magnetism', code:'6Pe.02', objective:'Make simple circuits and compare the brightness of lamps in series and parallel circuits.' },
  { grade:6, stage:6, strand:'Earth and Space', substrand:'Planet Earth', code:'6ESp.01', objective:'Know that rocks can be classified as metamorphic, igneous and sedimentary, and describe the identifying features of each type of rock.' },
  { grade:6, stage:6, strand:'Earth and Space', substrand:'Planet Earth', code:'6ESp.02', objective:'Describe the way fossils can form in sedimentary rocks.' },
  { grade:6, stage:6, strand:'Earth and Space', substrand:'Planet Earth', code:'6ESp.03', objective:'Know that there are different types of soils and they can be classified based on their clay, sand and organic content.' },
  { grade:6, stage:6, strand:'Earth and Space', substrand:'Planet Earth', code:'6ESp.04', objective:'Know that soil composition can change, which can support, or hinder, plant growth.' },
  { grade:6, stage:6, strand:'Earth and Space', substrand:'Cycles on Earth', code:'6ESc.01', objective:'Describe the rock cycle and the formation of metamorphic, igneous and sedimentary rocks in terms of solidification, erosion, sedimentation, burial, metamorphism and melting.' },
  { grade:6, stage:6, strand:'Earth and Space', substrand:'Earth in Space', code:'6ESs.01', objective:'Describe the relative position and movement of the planets, the Moon and the Sun in the Solar System.' },
  { grade:6, stage:6, strand:'Earth and Space', substrand:'Earth in Space', code:'6ESs.02', objective:'Observe and describe the changes in the appearance of the Moon over its monthly cycle.' },
];

async function seed() {
  console.log('Starting Science curriculum seed...');
  let count = 0;
  for (const item of curriculum) {
    await pool.query(
      `INSERT INTO curriculum (subject, grade, stage, strand, substrand, code, objective, curriculum_type)
       VALUES ($1, $2, $3, $4, $5, $6, $7, 'cambridge')
       ON CONFLICT DO NOTHING`,
      ['Science', item.grade, item.stage, item.strand, item.substrand, item.code, item.objective]
    );
    count++;
  }
  console.log(`✅ Seeded ${count} Science learning objectives!`);
  await pool.end();
}

seed().catch(err => {
  console.error('Seed error:', err);
  process.exit(1);
});
